FROM php:7.3-fpm

RUN echo "Clean and Update" \
    && apt-get clean && apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libzip-dev \
        zip \
        libfreetype6-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libpq-dev \
        libicu-dev \
        libxslt-dev \
        libsodium-dev \
        librabbitmq-dev \
        wget \
    && rm -rf /var/lib/apt/lists/*

RUN echo "Install extensions" \
    && pecl install xdebug \
    && pecl install amqp \
    && pecl install -o -f redis \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-configure bcmath --enable-bcmath \
    && docker-php-ext-configure intl \
    && docker-php-ext-install zip bcmath pcntl pdo_pgsql intl xsl sodium \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

RUN echo "Install composer" \
    && set -ex \
    && cd /tmp \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/bin --filename=composer \
    && chmod +x /usr/bin/composer \
    && rm -rf /tmp/*

RUN echo "Install Symfony CLI" \
    && wget https://get.symfony.com/cli/installer -O - | bash \
    && mv /root/.symfony/bin/symfony /usr/local/bin/symfony

RUN echo "Install GIT" \
    && apt-get clean && apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
    && rm -rf /var/lib/apt/lists/*

ARG USER=root
RUN groupadd -g 1000 ${USER} || echo "Group already exists."
RUN useradd -u 1000 -ms /bin/bash -g ${USER} ${USER} || echo "User already exists."
USER ${USER}

WORKDIR /var/www
